#pragma once

#include "quantum.h"
#include "../features/unicode.h"
#include "../features/custom_keycodes.h"

typedef struct {
    uint16_t base;
    uint16_t shift;
    uint16_t altgr;
    uint16_t shift_altgr;
} afnor_keycode_mapping_t;

static const afnor_keycode_mapping_t PROGMEM afnor_mappings[48];

bool process_afnor_keycodes(uint16_t keycode, keyrecord_t *record);

// Defining Afnor specific keycodes
#define FR_AF_AT         UM(UNICODE_AT)
#define FR_AF_AGRV       UM(UNICODE_AGRV)
#define FR_AF_EACU       UM(UNICODE_EACU)
#define FR_AF_EGRV       UM(UNICODE_EGRV)
#define FR_AF_ECIR       UM(UNICODE_ECIR)
#define FR_AF_LPRN       UM(UNICODE_LPRN)
#define FR_AF_RPRN       UM(UNICODE_RPRN)
#define FR_AF_LSQU       UM(UNICODE_LSQU)
#define FR_AF_RSQU       UM(UNICODE_RSQU)
#define FR_AF_LDAQ       UM(UNICODE_LDAQ)
#define FR_AF_RDAQ       UM(UNICODE_RDAQ)
#define FR_AF_QUOT       UM(UNICODE_QUOT)
#define FR_AF_CIRC       UM(UNICODE_CIRC)
#define FR_AF_A          UM(UNICODE_A)
#define FR_AF_Z          UM(UNICODE_Z)
#define FR_AF_E          UM(UNICODE_E)
#define FR_AF_R          UM(UNICODE_R)
#define FR_AF_T          UM(UNICODE_T)
#define FR_AF_Y          UM(UNICODE_Y)
#define FR_AF_U          UM(UNICODE_U)
#define FR_AF_I          UM(UNICODE_I)
#define FR_AF_O          UM(UNICODE_O)
#define FR_AF_P          UM(UNICODE_P)
#define FR_AF_MINS       UM(UNICODE_MINS)
#define FR_AF_PLUS       UM(UNICODE_PLUS)
#define FR_AF_Q          UM(UNICODE_Q)
#define FR_AF_S          UM(UNICODE_S)
#define FR_AF_D          UM(UNICODE_D)
#define FR_AF_F          UM(UNICODE_F)
#define FR_AF_G          UM(UNICODE_G)
#define FR_AF_H          UM(UNICODE_H)
#define FR_AF_J          UM(UNICODE_J)
#define FR_AF_K          UM(UNICODE_K)
#define FR_AF_L          UM(UNICODE_L)
#define FR_AF_M          UM(UNICODE_M)
#define FR_AF_SLSH       UM(UNICODE_SLSH)
#define FR_AF_ASTR       UM(UNICODE_ASTR)
#define FR_AF_LABK       UM(UNICODE_LABK)
#define FR_AF_W          UM(UNICODE_W)
#define FR_AF_X          UM(UNICODE_X)
#define FR_AF_C          UM(UNICODE_C)
#define FR_AF_V          UM(UNICODE_V)
#define FR_AF_B          UM(UNICODE_B)
#define FR_AF_N          UM(UNICODE_N)
#define FR_AF_DOT        UM(UNICODE_DOT)
#define FR_AF_COMM       UM(UNICODE_COMM)
#define FR_AF_COLN       UM(UNICODE_COLN)
#define FR_AF_SCLN       UM(UNICODE_SCLN)
#define FR_AF_HASH       UM(UNICODE_HASH)
#define FR_AF_1          UM(UNICODE_1)
#define FR_AF_2          UM(UNICODE_2)
#define FR_AF_3          UM(UNICODE_3)
#define FR_AF_4          UM(UNICODE_4)
#define FR_AF_5          UM(UNICODE_5)
#define FR_AF_6          UM(UNICODE_6)
#define FR_AF_7          UM(UNICODE_7)
#define FR_AF_8          UM(UNICODE_8)
#define FR_AF_9          UM(UNICODE_9)
#define FR_AF_0          UM(UNICODE_0)
#define FR_AF_DQUO       UM(UNICODE_DQUO)
#define FR_AF_DIAE       UM(UNICODE_DIAE)
#define FR_AF_NDSH       UM(UNICODE_NDSH)
#define FR_AF_PLMN       UM(UNICODE_PLMN)
#define FR_AF_BSLS       UM(UNICODE_BSLS)
#define FR_AF_HALF       UM(UNICODE_HALF)
#define FR_AF_RABK       UM(UNICODE_RABK)
#define FR_AF_QUES       UM(UNICODE_QUES)
#define FR_AF_EXLM       UM(UNICODE_EXLM)
#define FR_AF_ELLP       UM(UNICODE_ELLP)
#define FR_AF_EQL        UM(UNICODE_EQL)
#define FR_AF_BREV       UM(UNICODE_BREV)
#define FR_AF_SECT       UM(UNICODE_SECT)
#define FR_AF_ACUT       UM(UNICODE_ACUT)
#define FR_AF_GRV        UM(UNICODE_GRV)
#define FR_AF_AMPR       UM(UNICODE_AMPR)
#define FR_AF_LBRC       UM(UNICODE_LBRC)
#define FR_AF_RBRC       UM(UNICODE_RBRC)
#define FR_AF_MACR       UM(UNICODE_MACR)
#define FR_AF_UNDS       UM(UNICODE_UNDS)
#define FR_AF_LDQU       UM(UNICODE_LDQU)
#define FR_AF_RDQU       UM(UNICODE_RDQU)
#define FR_AF_DEG        UM(UNICODE_DEG)
#define FR_AF_CARN       UM(UNICODE_CARN)
#define FR_AF_AE         UM(UNICODE_AE)
#define FR_AF_PND        UM(UNICODE_PND)
#define FR_AF_EURO       UM(UNICODE_EURO)
#define FR_AF_REGD       UM(UNICODE_REGD)
#define FR_AF_LCBR       UM(UNICODE_LCBR)
#define FR_AF_RCBR       UM(UNICODE_RCBR)
#define FR_AF_UGRV       UM(UNICODE_UGRV)
#define FR_AF_DOTA       UM(UNICODE_DOTA)
#define FR_AF_OE         UM(UNICODE_OE)
#define FR_AF_PERC       UM(UNICODE_PERC)
#define FR_AF_MMNS       UM(UNICODE_MMNS)
#define FR_AF_DAGG       UM(UNICODE_DAGG)
#define FR_AF_THET       UM(UNICODE_THET)
#define FR_AF_SS         UM(UNICODE_SS)
#define FR_AF_DLR        UM(UNICODE_DLR)
#define FR_AF_CURR       UM(UNICODE_CURR)
#define FR_AF_DGRK       UM(UNICODE_DGRK)
#define FR_AF_EU         UM(UNICODE_EU)
#define FR_AF_DSLS       UM(UNICODE_DSLS)
#define FR_AF_PIPE       UM(UNICODE_PIPE)
#define FR_AF_INFN       UM(UNICODE_INFN)
#define FR_AF_DIV        UM(UNICODE_DIV)
#define FR_AF_MUL        UM(UNICODE_MUL)
#define FR_AF_LEQL       UM(UNICODE_LEQL)
#define FR_AF_EZH        UM(UNICODE_EZH)
#define FR_AF_COPY       UM(UNICODE_COPY)
#define FR_AF_CCED       UM(UNICODE_CCED)
#define FR_AF_CEDL       UM(UNICODE_CEDL)
#define FR_AF_DMNS       UM(UNICODE_DMNS)
#define FR_AF_DTIL       UM(UNICODE_DTIL)
#define FR_AF_IQUE       UM(UNICODE_IQUE)
#define FR_AF_IEXL       UM(UNICODE_IEXL)
#define FR_AF_MDDT       UM(UNICODE_MDDT)
#define FR_AF_AEQL       UM(UNICODE_AEQL)
#define FR_AF_IBRV       UM(UNICODE_IBRV)
#define FR_AF_AGRV_CAPS  UM(UNICODE_AGRV_CAPS)
#define FR_AF_EACU_CAPS  UM(UNICODE_EACU_CAPS)
#define FR_AF_EGRV_CAPS  UM(UNICODE_EGRV_CAPS)
#define FR_AF_ECIR_CAPS  UM(UNICODE_ECIR_CAPS)
#define FR_AF_DACU       UM(UNICODE_DACU)
#define FR_AF_DGRV       UM(UNICODE_DGRV)
#define FR_AF_MDSH       UM(UNICODE_MDSH)
#define FR_AF_LSAQ       UM(UNICODE_LSAQ)
#define FR_AF_RSAQ       UM(UNICODE_RSAQ)
#define FR_AF_RNGA       UM(UNICODE_RNGA)
#define FR_AF_AE_CAPS    UM(UNICODE_AE_CAPS)
#define FR_AF_TM         UM(UNICODE_TM)
#define FR_AF_UGRV_CAPS  UM(UNICODE_UGRV_CAPS)
#define FR_AF_DOTB       UM(UNICODE_DOTB)
#define FR_AF_OE_CAPS    UM(UNICODE_OE_CAPS)
#define FR_AF_PERM       UM(UNICODE_PERM)
#define FR_AF_NBHY       UM(UNICODE_NBHY)
#define FR_AF_DDAG       UM(UNICODE_DDAG)
#define FR_AF_SS_CAPS    UM(UNICODE_SS_CAPS)
#define FR_AF_MACB       UM(UNICODE_MACB)
#define FR_AF_SQRT       UM(UNICODE_SQRT)
#define FR_AF_QRTR       UM(UNICODE_QRTR)
#define FR_AF_GEQL       UM(UNICODE_GEQL)
#define FR_AF_EZH_CAPS   UM(UNICODE_EZH_CAPS)
#define FR_AF_CCED_CAPS  UM(UNICODE_CCED_CAPS)
#define FR_AF_OGON       UM(UNICODE_OGON)
#define FR_AF_DCMM       UM(UNICODE_DCMM)
#define FR_AF_NEQL       UM(UNICODE_NEQL)
